### ISSUE TITLE
Missing peerDeps after installing non-base package

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/eslint-config#12]
When using yarn, with the `npx install-peerdeps ...` instructions, it will not install peerDeps from "nested" packages.
This means that the peerDeps from `eslint-config-base` are not installed in your project.

A solution would be to include the peerDeps from the `base` package in the `react` and `vue` packages as well?

Another option would be to also run `npx install-peerdeps --dev @mediamonks/eslint-config-base`, but that would add `@mediamonks/eslint-config-base` to the project's `package.json`, which isn't needed (since it's already a direct dependency)

**Comment by psimk** [comment]
> Another option would be to also run npx install-peerdeps --dev @mediamonks/eslint-config-base, but that would add @mediamonks/eslint-config-base to the project's package.json, which isn't needed (since it's already a direct dependency)

It seems that `install-peerdeps` allows passing a `--only-peers` flag that will install only the peer dependencies of the specified package. So I think we can update our `README.md` to note this, so that `yarn` users can still use our eslint configs.
