### ISSUE TITLE
Configure `import/no-extraneous-dependencies` for test code

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/eslint-config#15]
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md

When writing unit tests, you sometimes install and use packages that are not part of the published library, so you install them as `devDependencies`. `eslint` doesn't know that, so it will complain that they should be normal `dependencies`.

Something similar could be the case for scripts and other tools you write.

For "projects" you can get away with moving these to normal dependencies, since everything should be installed anyway.

For libraries you do care about what is placed where, since it determines if it will be installed when your library is used by another project or library.

Currently I've added this to my `.eslintrc`.

```
  rules: {
    "import/no-extraneous-dependencies": ["error", {"devDependencies": ["**/*.test.ts", "**/test-utils/**/*.ts"]}]
  },
```

If we make this more generic, we might be able to include it in the default eslint-config?

Thoughts and suggestions are welcome!

**Comment by psimk** [comment]
Should we also add an exception to `'**/*.stories.ts'`?
