### ISSUE TITLE
Turn off `consistent-return` for TS files

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/eslint-config#16]
Since TS already checks if your function's return type is correct (which you should always define), [this JS rule](https://eslint.org/docs/rules/consistent-return) doesn't make sense.

In cases where your function can return `string | undefined`, you would have to explicitly `return undefined` in all locations you would do (early) returns, or even at the end of the function where undefined is implicitly returned.

**Comment by psimk** [comment]
Instead of outright disabling this rule, I think we can specify the `treatUndefinedAsUnspecified` option to allow implicit `undefined ` returns (see https://eslint.org/docs/rules/consistent-return#treatundefinedasunspecified).

**Comment by ThaNarie** [comment]
Looks like that **only** allows you to leave out the implicit return (the one at the end of the function), but would **still** **require** `return undefined` for early returns – where with TS you can just do `return`.
