### ISSUE TITLE
Disable `unicorn/prevent-abbreviations` for imports

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/eslint-config#17]
By default (value `internal`), [this rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md) reports/renames imports from internal modules.

```js
// checkDefaultAndNamespaceImports
import * as err from './err';
import err from '/err';

// checkShorthandImports
import { prop } from './foo';
```

However, it will report the same issue where this is exported, where it _should_ be fixed instead.

If there is a case where I want to keep using the abbreviated version for some reason, I can ignore the place where I export it.
But now I would also have to ignore it everywhere it's imported.

I suggest to disable this rule for imports, since it's redundant.
```js
"unicorn/prevent-abbreviations": ["error", { checkDefaultAndNamespaceImports : false, checkShorthandImports: false }],
```

**Comment by psimk** [comment]
> it will report the same issue where this is exported, where it should be fixed instead.

I agree with this, if you look at imports and exports as a consumer - provider relationship, then it makes sense that the provider (the exporting module) is responsible for amending the linting issue, not the consumer (the importing module).
