### ISSUE TITLE
Should we disallow absolute paths in imports?

### ISSUE THREAD

**Issue by leroykorterink** [mediamonks/eslint-config#31]
We should use always use relative paths for file imports, absolute paths should only be used for modules. 

Not sure how we should enforce this, an easy solution would be to restrict importing from `src` using https://eslint.org/docs/rules/no-restricted-imports. `src` might not be the right folder (or cover all paths) for some skeletons so maybe it should dynamically get all folder names at the `baseUrl` if there's a `tsconfig`.

Sometimes the `tsconfig` `paths` are also changed to make absolute imports possible, there's not really a rule to prevent this afaik. Changing the `paths` is something we should actively discourage (there could be valid reasons for custom paths though).

**Comment by leroykorterink** [comment]
Why relative paths you may ask? Relative paths will never have a conflict with an installed module and are ofter shorter to type.

The absolute paths will have a name conflict if a module called `storybook` is installed (You really should install `@storybook/cli` but I'm trying to prove a point 😅  . It's possible that installing a module could have unwanted side effects  in a project because of using absolute paths (e.g. stuff not working at all, or unwanted code accidentally imported 🔓 ).

```
// Real example of a potential path conflict
Import { addViewportDecorator } from ‘storybook/decorators/addViewportDecorator’
````

Absolute imports do prevent “relative path hell” e.g. `../../../../util/padRight`. Relative imports might become very long, but this is usually an indication that the folder structure in the project should be improved. Our code editors should auto-complete imports, so writing out paths is automated.

```
// Relative paths are usually shorter than absolute paths
import { Button } from '@/components/molecules/Button';

// From another molecule
import { Button } from '../Button';

// From an organism or atom
import { Button } from '../../molecule/Button';
```

**Comment by ardakkk** [comment]
Can we use [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) and [/eslint-import-resolver-typescript](https://github.com/import-js/eslint-import-resolver-typescript) and add it as `configs/eslint-config-import` package? @leroykorterink @ThaNarie

**Comment by ardakkk** [comment]
I thought that we decompose each eslint config to extend more dynamically
