### ISSUE TITLE
Should we eslint-plugin-jsx-a11y plugin separate package?

### ISSUE THREAD

**Issue by ardakkk** [mediamonks/eslint-config#36]
Create `config/jsx-a11y` package and add rules for [`jsx-a11y`](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) plugin to extend it separately

**Comment by ThaNarie** [comment]
Could you clarify your use case? Where would you need it for? And why can't you use the base eslint-config that already includes that plugin?

https://github.com/mediamonks/eslint-config/blob/23c16a7ffa3a9c3f563f9544ae89ed5da1883739/configs/base/index.js#L4
