### ISSUE TITLE
Add a linting rule that forbids the usages of a one length Tuple ([MyType])

### ISSUE THREAD

**Issue by ThijsTyZ** [mediamonks/eslint-config#6]
Add a linting rule that forbids the usages of a one length Tuple (`[MyType]`), since this is barely used and a frequently made mistake if you actually wanted to write a regular Array. Especially in project with GraphQL, since `[MyType]` is how you define an Array in GraphQL

**Comment by mmnathan** [comment]
Closing as stale due a lack of activity and we already use `Array<T>` over `T[]` to avoid syntax ambiguity.
