### ISSUE TITLE
react/jsx-no-literals conflicts with prettier

### ISSUE THREAD

**Issue by hjeti** [mediamonks/eslint-config#64]
This rule forces to use an ugly curly braces syntax that is not supported by prettier so every time you run prettier all your changes are removed. So let's disable this rule to avoid conflicts and adding a lot of eslint disables in projects.

This should be valid jsx:

```jsx
<Button>Label</Button>
```

**Comment by ThaNarie** [comment]
I think the intent of this rule is **not** to write `<Button>{'Label'}</Button>`, but rather to have all content come external places (like translation files, or api data).
And in turn, it would "warn" you if any copy is still hardcoded, and should be moved to an external source.

For small tools and prototyping this is not working, so there the rule should be disabled in the project.

I can imagine that during the start of a project, you might run into these scenarios, and it would be annoying :)

What I don't know, is what percentage of project work is dynamic vs static. If it's fairly equal for most projects, or if it varies al lot.

Based on that we have 3 options:
1. keep as is, and adjust per use case
2. disable here, but add to skeletons where we know it helps (and can be turned off easily by removing it from the config on a per-project basis)
3. disable everywhere, and let it be opt-in on a per-project basis (where we know all/most copy is coming from external sources)

**Comment by mmnathan** [comment]
Even for small projects i feel a `data/staticCopy.ts`-esque file still makes sense the same way we still (probably) wanna use css vars or `.env` files.
