### ISSUE TITLE
Setup Actions

### ISSUE THREAD

**Issue by psimk** [mediamonks/eslint-config#7]
Since the only purpose of this repository is to store our eslint configs, instead of publishing each package ourselves, we should setup an action to publish them whenever a branch is merged into `main`.

**Comment by ThijsTyZ** [comment]
Agree

**Comment by psimk** [comment]
This has been completed in https://github.com/mediamonks/eslint-config/commit/4c7c906ff363e49fd1e52278b37efaf4c7199ee4
